package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.entity.SearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 鑱婂ぉ澶勭悊鏈嶅姟
 * 璐熻矗澶勭悊WebSocket鑱婂ぉ娑堟伅鍜岀鐞嗗璇濆巻鍙? * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final int MAX_SNIPPET_LEN = 300;
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ObjectMapper objectMapper;
    private final int adaptiveRecallTopK;
    private final int adaptiveMinTopK;
    private final int adaptiveMaxTopK;
    private final double adaptiveScoreRatio;
    private final int adaptiveContextCharBudget;
    
    // 鐢ㄤ簬瀛樺偍姣忎釜浼氳瘽鐨勫畬鏁村搷搴?    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 鐢ㄤ簬璺熻釜姣忎釜浼氳瘽鐨勫搷搴斿畬鎴愮姸鎬?    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 鍋滄鏍囧織 - 绠€鍗曟柟妗?    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 鐢ㄤ簬瀛樺偍姣忎釜浼氳瘽鐨勫紩鐢ㄦ槧灏勶細sessionId -> {referenceNumber -> fileMd5}
    private final Map<String, Map<Integer, String>> sessionReferenceMappings = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      @Value("${ai.retrieval.adaptive-recall-top-k:12}") int adaptiveRecallTopK,
                      @Value("${ai.retrieval.adaptive-min-top-k:2}") int adaptiveMinTopK,
                      @Value("${ai.retrieval.adaptive-max-top-k:6}") int adaptiveMaxTopK,
                      @Value("${ai.retrieval.adaptive-score-ratio:0.82}") double adaptiveScoreRatio,
                      @Value("${ai.retrieval.adaptive-context-char-budget:1200}") int adaptiveContextCharBudget) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.objectMapper = new ObjectMapper();
        this.adaptiveRecallTopK = adaptiveRecallTopK;
        this.adaptiveMinTopK = adaptiveMinTopK;
        this.adaptiveMaxTopK = adaptiveMaxTopK;
        this.adaptiveScoreRatio = adaptiveScoreRatio;
        this.adaptiveContextCharBudget = adaptiveContextCharBudget;
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("寮€濮嬪鐞嗘秷鎭紝鐢ㄦ埛ID: {}, 浼氳瘽ID: {}", userId, session.getId());
        try {
            // 1. 鑾峰彇鎴栧垱寤轰細璇?ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("浼氳瘽ID: {}, 鐢ㄦ埛ID: {}", conversationId, userId);
            
            // 涓哄綋鍓嶄細璇濆垱寤哄搷搴旀瀯寤哄櫒
            responseBuilders.put(session.getId(), new StringBuilder());
            // 鍒涘缓涓€涓狢ompletableFuture鏉ヨ窡韪搷搴斿畬鎴愮姸鎬?            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 鑾峰彇瀵硅瘽鍘嗗彶
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("鑾峰彇鍒?{} 鏉″巻鍙插璇?, history.size());
            
            // 3. 鎵ц甯︽潈闄愯繃婊ょ殑娣峰悎鎼滅储
            List<SearchResult> searchCandidates = searchService.searchWithPermission(userMessage, userId, adaptiveRecallTopK);
            List<SearchResult> searchResults = selectAdaptiveTopK(userMessage, searchCandidates);
            logger.debug("鎼滅储鍊欓€夋暟閲? {}, 鑷€傚簲鍚庢暟閲? {}", searchCandidates.size(), searchResults.size());
            
            // 4. 鏋勫缓涓婁笅鏂?            String context = buildContext(searchResults, session.getId());
            
            // 5. 璋冪敤 DeepSeek API 骞跺鐞嗘祦寮忓搷搴?            logger.info("璋冪敤DeepSeek API鐢熸垚鍥炲");
            deepSeekClient.streamResponse(userMessage, context, history, 
                chunk -> {
                    // 绱Н鍝嶅簲鍐呭
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    // 澶勭悊閿欒骞跺畬鎴恌uture
                    handleError(session, error);
                    // 鍙戦€佸搷搴斿畬鎴愰€氱煡锛堥敊璇儏鍐碉級
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 娓呯悊浼氳瘽鍝嶅簲鏋勫缓鍣?                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                });
            
            // 6. 鍚姩涓€涓悗鍙颁换鍔℃鏌ュ苟鏍囪鍝嶅簲瀹屾垚
            new Thread(() -> {
                try {
                    // 绛夊緟鏈€澶?0绉掞紝缁橝PI瓒冲鐨勫搷搴旀椂闂?                    Thread.sleep(3000); // 鍏堢瓑寰?绉掗挓锛岃API鏈夋椂闂村紑濮嬪搷搴?                    
                    // 鑾峰彇褰撳墠绱Н鐨勫搷搴斿唴瀹?                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    
                    // 濡傛灉鍝嶅簲鏋勫缓鍣ㄥ瓨鍦ㄥ苟涓斿凡鏈夊唴瀹癸紝璁や负鍝嶅簲宸插畬鎴?                    if (responseBuilder != null) {
                        // 璁板綍鏈€鍚?绉掔殑鍝嶅簲鍙樺寲锛屾娴嬫槸鍚﹀仠姝㈠闀?                        String lastResponse = responseBuilder.toString();
                        int lastLength = lastResponse.length();
                        
                        Thread.sleep(2000); // 鍐嶇瓑寰?绉?                        
                        // 鍐嶆妫€鏌ユ槸鍚︽湁鏂板唴瀹?                        if (responseBuilder.length() == lastLength) {
                            // 娌℃湁鏂板唴瀹癸紝鍙互璁や负鍝嶅簲宸插畬鎴?                            responseFuture.complete(responseBuilder.toString());
                            logger.info("DeepSeek鍝嶅簲宸插畬鎴愶紝闀垮害: {}", responseBuilder.length());
                            
                            // 鍙戦€佸搷搴斿畬鎴愰€氱煡
                            sendCompletionNotification(session);
                            
                            // 鏇存柊瀵硅瘽鍘嗗彶
                            String completeResponse = responseBuilder.toString();
                            updateConversationHistory(conversationId, userMessage, completeResponse);
                            
                            // 杈撳嚭瀵硅瘽瀛樺偍淇℃伅浠ヤ究璋冭瘯
                            String redisKey = "user:" + userId + ":current_conversation";
                            logger.info("瀵硅瘽瀛樺偍淇℃伅 - Redis閿? {}, 鍊? {}", redisKey, conversationId);
                            
                            // 娓呯悊浼氳瘽鍝嶅簲鏋勫缓鍣?                            responseBuilders.remove(session.getId());
                            responseFutures.remove(session.getId());
                            logger.info("娑堟伅澶勭悊瀹屾垚锛岀敤鎴稩D: {}", userId);
                        } else {
                            // 浠嶆湁鏂板唴瀹癸紝缁х画绛夊緟
                            logger.debug("鍝嶅簲浠嶅湪缁х画锛岀瓑寰呭畬鎴?..");
                            // 鍐嶇瓑寰呮渶澶?5绉?                            for (int i = 0; i < 5; i++) {
                                Thread.sleep(5000);
                                if (responseBuilder != null) {
                                    lastLength = responseBuilder.length();
                                    // 鍐嶆妫€鏌?绉掑唴鏄惁鏈夋柊鍐呭
                                    Thread.sleep(2000);
                                    if (responseBuilder.length() == lastLength) {
                                        // 娌℃湁鏂板唴瀹癸紝鍙互璁や负鍝嶅簲宸插畬鎴?                                        responseFuture.complete(responseBuilder.toString());
                                        
                                        // 鍙戦€佸搷搴斿畬鎴愰€氱煡
                                        sendCompletionNotification(session);
                                        
                                        // 鏇存柊瀵硅瘽鍘嗗彶
                                        String completeResponse = responseBuilder.toString();
                                        updateConversationHistory(conversationId, userMessage, completeResponse);
                                        
                                        // 杈撳嚭瀵硅瘽瀛樺偍淇℃伅浠ヤ究璋冭瘯
                                        String redisKey = "user:" + userId + ":current_conversation";
                                        logger.info("瀵硅瘽瀛樺偍淇℃伅 - Redis閿? {}, 鍊? {}", redisKey, conversationId);
                                        
                                        // 娓呯悊浼氳瘽鍝嶅簲鏋勫缓鍣?                                        responseBuilders.remove(session.getId());
                                        responseFutures.remove(session.getId());
                                        logger.info("娑堟伅澶勭悊瀹屾垚锛岀敤鎴稩D: {}", userId);
                                        return;
                                    }
                                }
                            }
                            
                            // 濡傛灉缁忚繃澶氭妫€鏌ヤ粛鏈畬鎴愶紝寮哄埗瀹屾垚
                            if (!responseFuture.isDone()) {
                                responseFuture.complete(responseBuilder.toString());
                                
                                // 鍙戦€佸搷搴斿畬鎴愰€氱煡
                                sendCompletionNotification(session);
                                
                                // 鏇存柊瀵硅瘽鍘嗗彶
                                String completeResponse = responseBuilder.toString();
                                updateConversationHistory(conversationId, userMessage, completeResponse);
                                
                                // 杈撳嚭瀵硅瘽瀛樺偍淇℃伅浠ヤ究璋冭瘯
                                String redisKey = "user:" + userId + ":current_conversation";
                                logger.info("瀵硅瘽瀛樺偍淇℃伅 - Redis閿? {}, 鍊? {}", redisKey, conversationId);
                                
                                // 娓呯悊浼氳瘽鍝嶅簲鏋勫缓鍣?                                responseBuilders.remove(session.getId());
                                responseFutures.remove(session.getId());
                                logger.info("娑堟伅澶勭悊寮哄埗瀹屾垚锛岀敤鎴稩D: {}", userId);
                            }
                        }
                    } else {
                        logger.warn("鍝嶅簲鏋勫缓鍣ㄤ负绌猴紝鍙兘鍑虹幇浜嗛敊璇紝浼氳瘽ID: {}", session.getId());
                        RuntimeException exception = new RuntimeException("鍝嶅簲鏋勫缓鍣ㄤ负绌?);
                        responseFuture.completeExceptionally(exception);
                        // 鍙戦€侀敊璇秷鎭?                        handleError(session, exception);
                    }
                } catch (Exception e) {
                    logger.error("妫€鏌ュ搷搴斿畬鎴愭椂鍑洪敊: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    
                    // 娓呯悊浼氳瘽鍝嶅簲鏋勫缓鍣?                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                }
            }).start();
            
        } catch (Exception e) {
            logger.error("澶勭悊娑堟伅閿欒: {}", e.getMessage(), e);
            handleError(session, e);
            // 娓呯悊浼氳瘽鍝嶅簲鏋勫缓鍣?            responseBuilders.remove(session.getId());
            // 娓呯悊鍝嶅簲future
            CompletableFuture<String> future = responseFutures.remove(session.getId());
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

    private List<SearchResult> selectAdaptiveTopK(String userMessage, List<SearchResult> candidates) {
        if (candidates == null || candidates.isEmpty()) {
            return new ArrayList<>();
        }

        int desiredTopK = Math.min(adaptiveMaxTopK, Math.max(adaptiveMinTopK, estimateDesiredTopK(userMessage)));
        Double topScore = candidates.get(0).getScore();
        double scoreThreshold = topScore != null ? topScore * adaptiveScoreRatio : Double.NEGATIVE_INFINITY;

        List<SearchResult> selected = new ArrayList<>();
        int usedChars = 0;

        for (int i = 0; i < candidates.size(); i++) {
            SearchResult candidate = candidates.get(i);
            int estimatedChars = estimateContextChars(candidate);
            Double score = candidate.getScore();

            if (selected.size() >= adaptiveMaxTopK) {
                break;
            }

            boolean belowMinTarget = selected.size() < desiredTopK;
            boolean withinScoreWindow = score == null || score >= scoreThreshold;
            boolean withinContextBudget = usedChars + estimatedChars <= adaptiveContextCharBudget;

            if (!belowMinTarget && (!withinScoreWindow || !withinContextBudget)) {
                logger.debug("鑷€傚簲 Top-K 鎴柇锛宺ank={}, score={}, threshold={}, usedChars={}, candidateChars={}",
                        i + 1, score, scoreThreshold, usedChars, estimatedChars);
                break;
            }

            selected.add(candidate);
            usedChars += estimatedChars;
        }

        if (selected.isEmpty()) {
            selected.add(candidates.get(0));
        }

        logger.info("鑷€傚簲 Top-K 閫夋嫨瀹屾垚锛歞esired={}, actual={}, threshold={}, contextChars={}/{}",
                desiredTopK, selected.size(), scoreThreshold, usedChars, adaptiveContextCharBudget);
        return selected;
    }

    private int estimateDesiredTopK(String userMessage) {
        if (userMessage == null || userMessage.isBlank()) {
            return adaptiveMinTopK;
        }

        int desired = adaptiveMinTopK;
        int messageLength = userMessage.length();

        if (messageLength > 18) {
            desired++;
        }
        if (messageLength > 36) {
            desired++;
        }

        if (containsAny(userMessage, "\u5982\u4f55", "\u600e\u4e48", "\u6d41\u7a0b", "\u6b65\u9aa4", "\u4e3a\u4ec0\u4e48")) {
            desired++;
        }
        if (containsAny(userMessage, "\u6bd4\u8f83", "\u533a\u522b", "\u5dee\u5f02", "\u4ee5\u53ca", "\u540c\u65f6", "\u5206\u522b")) {
            desired++;
        }

        return desired;
    }

    private boolean containsAny(String text, String... keywords) {
        for (String keyword : keywords) {
            if (text.contains(keyword)) {
                return true;
            }
        }
        return false;
    }

    private int estimateContextChars(SearchResult result) {
        if (result == null || result.getTextContent() == null) {
            return 32;
        }
        int snippetChars = Math.min(result.getTextContent().length(), MAX_SNIPPET_LEN);
        String fileName = result.getFileName() != null ? result.getFileName() : "unknown";
        String fileMd5 = result.getFileMd5() != null ? result.getFileMd5() : "";
        return snippetChars + fileName.length() + fileMd5.length() + 24;
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("涓虹敤鎴?{} 鍒涘缓鏂扮殑浼氳瘽ID: {}", userId, conversationId);
        } else {
            logger.info("鑾峰彇鍒扮敤鎴?{} 鐨勭幇鏈変細璇滻D: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("浼氳瘽 {} 娌℃湁鍘嗗彶璁板綍", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("璇诲彇鍒颁細璇?{} 鐨?{} 鏉″巻鍙茶褰?, conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("瑙ｆ瀽瀵硅瘽鍘嗗彶鍑洪敊: {}, 浼氳瘽ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        // 鑾峰彇褰撳墠鏃堕棿鎴?        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 娣诲姞鐢ㄦ埛娑堟伅锛堝甫鏃堕棿鎴筹級
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        // 娣诲姞鍔╂墜鍥炲锛堝甫鏃堕棿鎴筹級
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);
        
        // 闄愬埗鍘嗗彶璁板綍闀垮害锛屼繚鐣欐渶杩戠殑20鏉℃秷鎭?        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("鏇存柊浼氳瘽鍘嗗彶锛屼細璇滻D: {}, 鎬绘秷鎭暟: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("搴忓垪鍖栧璇濆巻鍙插嚭閿? {}, 浼氳瘽ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults, String sessionId) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 杩斿洖绌哄瓧绗︿覆锛岃 DeepSeekClient 鎸?鏃犳绱㈢粨鏋?閫昏緫澶勭悊
            return "";
        }

        // 鍒涘缓褰撳墠浼氳瘽鐨勫紩鐢ㄦ槧灏?        Map<Integer, String> referenceMapping = new HashMap<>();

        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "鈥?;
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            String fileMd5 = result.getFileMd5();

            // 鏍煎紡锛歔1] (test1.txt | MD5:abc123def456) 鏂囦欢鍐呭...
            // 杩欐牱AI鍜岀敤鎴烽兘鑳介€氳繃MD5鍖哄垎鍚屽悕鏂囦欢
            context.append(String.format("[%d] (%s | MD5:%s) %s\n", i + 1, fileLabel, fileMd5, snippet));

            // 淇濆瓨寮曠敤缂栧彿鍒癕D5鐨勬槧灏?            if (fileMd5 != null) {
                referenceMapping.put(i + 1, fileMd5);
                // 璇︾粏鏃ュ織锛氳褰曟瘡涓紩鐢ㄧ紪鍙风殑鏄犲皠鍏崇郴
                logger.info("寮曠敤鏄犲皠: sessionId={}, 寮曠敤缂栧彿#{}={}, 鏂囦欢鍚?{}, MD5={}",
                    sessionId, i + 1, fileLabel, fileMd5);
            }
        }

        // 淇濆瓨褰撳墠浼氳瘽鐨勫紩鐢ㄦ槧灏?        sessionReferenceMappings.put(sessionId, referenceMapping);
        logger.info("淇濆瓨浼氳瘽 {} 鐨勫紩鐢ㄦ槧灏勶紝鍏?{} 鏉? {}", sessionId, referenceMapping.size(), referenceMapping);

        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 妫€鏌ユ槸鍚﹂渶瑕佸仠姝㈠彂閫?            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("妫€娴嬪埌鍋滄鏍囧織锛岃烦杩囧彂閫佸搷搴斿潡");
                return;
            }
            
            // 灏哻hunk鍖呰鎴怞SON鏍煎紡锛屽尮閰嶅墠绔湡鏈涚殑鏁版嵁缁撴瀯
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("鍙戦€佸搷搴斿潡鍒颁細璇?{}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("鍙戦€佸搷搴斿潡澶辫触: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "鍝嶅簲宸插畬鎴?,
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("鍙戦€佸畬鎴愰€氱煡鍒颁細璇?{}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("宸插彂閫佸搷搴斿畬鎴愰€氱煡鍒颁細璇? {}", session.getId());
        } catch (Exception e) {
            logger.error("鍙戦€佸畬鎴愰€氱煡澶辫触: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI鏈嶅姟閿欒: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI鏈嶅姟鏆傛椂涓嶅彲鐢紝璇风◢鍚庨噸璇?);
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("鍙戦€侀敊璇秷鎭埌浼氳瘽 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("宸插彂閫侀敊璇秷鎭埌浼氳瘽: {}", session.getId());
        } catch (Exception e) {
            logger.error("鍙戦€侀敊璇秷鎭け璐? {}", e.getMessage(), e);
        }
    }

    /**
     * 鍋滄鍝嶅簲
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("鏀跺埌鍋滄璇锋眰锛岀敤鎴稩D: {}, 浼氳瘽ID: {}", userId, sessionId);

        // 璁剧疆鍋滄鏍囧織
        stopFlags.put(sessionId, true);

        // 鍙戦€佸仠姝㈢‘璁?        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop",
                "message", "鍝嶅簲宸插仠姝?,
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("鍙戦€佸仠姝㈢‘璁ゅ埌浼氳瘽 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("宸插彂閫佸仠姝㈢‘璁わ紝浼氳瘽ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("鍙戦€佸仠姝㈢‘璁ゅけ璐? {}", e.getMessage(), e);
        }

        // 娓呯悊鍋滄鏍囧織锛堝欢杩熸竻鐞嗭紝閬垮厤褰卞搷褰撳墠鍝嶅簲锛?        new Thread(() -> {
            try {
                Thread.sleep(2000); // 绛夊緟2绉?                stopFlags.remove(sessionId);
                logger.debug("宸叉竻鐞嗗仠姝㈡爣蹇楋紝浼氳瘽ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    /**
     * 鏍规嵁浼氳瘽ID鍜屽紩鐢ㄧ紪鍙疯幏鍙栨枃浠禡D5
     *
     * @param sessionId WebSocket浼氳瘽ID
     * @param referenceNumber 寮曠敤缂栧彿
     * @return 鏂囦欢MD5锛屽鏋滄壘涓嶅埌鍒欒繑鍥瀗ull
     */
    public String getReferenceMd5(String sessionId, int referenceNumber) {
        logger.info("鏌ヨ寮曠敤MD5: sessionId={}, referenceNumber=#{}", sessionId, referenceNumber);

        Map<Integer, String> referenceMapping = sessionReferenceMappings.get(sessionId);
        if (referenceMapping == null) {
            logger.error("鏈壘鍒颁細璇?{} 鐨勫紩鐢ㄦ槧灏勶紝褰撳墠鎵€鏈変細璇? {}", sessionId, sessionReferenceMappings.keySet());
            return null;
        }

        logger.info("浼氳瘽 {} 鐨勫紩鐢ㄦ槧灏勫唴瀹? {}", sessionId, referenceMapping);

        String fileMd5 = referenceMapping.get(referenceNumber);
        if (fileMd5 == null) {
            logger.error("浼氳瘽 {} 涓湭鎵惧埌寮曠敤缂栧彿 #{}, 鍙敤鐨勫紩鐢ㄧ紪鍙? {}", sessionId, referenceNumber, referenceMapping.keySet());
            return null;
        }

        logger.info("鎴愬姛鎵惧埌寮曠敤鏄犲皠: sessionId={}, referenceNumber=#{}, fileMd5={}", sessionId, referenceNumber, fileMd5);
        return fileMd5;
    }

    /**
     * 娓呯悊浼氳瘽鐨勫紩鐢ㄦ槧灏?     *
     * @param sessionId WebSocket浼氳瘽ID
     */
    public void clearSessionReferenceMapping(String sessionId) {
        Map<Integer, String> removed = sessionReferenceMappings.remove(sessionId);
        if (removed != null) {
            logger.info("娓呯悊浼氳瘽 {} 鐨勫紩鐢ㄦ槧灏勶紝鍏?{} 鏉?, sessionId, removed.size());
        }
    }
}
